name: GitHub Pages Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --minify --buildDrafts
    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@v4.2.5
    #   with:
    #       branch: gh-pages # The branch the action should deploy to.
    #       folder: public # The folder the action should deploy.